FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements/requirements.txt .
RUN pip3 install -r requirements.txt

COPY requirements/requirements-test.txt .
RUN pip3 install -r requirements-test.txt

COPY main.py .
COPY src/ /app/src/
COPY tests/ /app/tests/

RUN useradd -m myuser
USER myuser

EXPOSE 5000
CMD ["pytest", "-p", "no:cacheprovider"]